### ISSUE TITLE
Java util logger not showing full stack trace

### ISSUE THREAD

**Issue by stuart-warren** [stuart-warren/logit#42]
Not showing past "Caused by" lines:

```
23-Oct-2013 23:08:15 org.apache.catalina.core.StandardService initInternal
SEVERE: Failed to initialize connector [Connector[HTTP/1.1-8080]]
org.apache.catalina.LifecycleException: Failed to initialize component [Connector[HTTP/1.1-8080]]
    at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:106)
    at org.apache.catalina.core.StandardService.initInternal(StandardService.java:559)
    at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
    at org.apache.catalina.core.StandardServer.initInternal(StandardServer.java:815)
    at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
    at org.apache.catalina.startup.Catalina.load(Catalina.java:594)
    at org.apache.catalina.startup.Catalina.load(Catalina.java:619)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:616)
    at org.apache.catalina.startup.Bootstrap.load(Bootstrap.java:281)
    at org.apache.catalina.startup.Bootstrap.main(Bootstrap.java:449)
Caused by: org.apache.catalina.LifecycleException: Protocol handler initialization failed
    at org.apache.catalina.connector.Connector.initInternal(Connector.java:958)
    at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
    ... 12 more
Caused by: java.lang.NullPointerException
    at com.stuartwarren.logit.layout.Log.addField(Log.java:240)
    at com.stuartwarren.logit.jul.Layout.doFormat(Layout.java:96)
    at com.stuartwarren.logit.jul.Layout.format(Layout.java:71)
    at com.stuartwarren.logit.jul.ZmqAppender.publish(ZmqAppender.java:75)
    at java.util.logging.Logger.log(Logger.java:530)
    at java.util.logging.Logger.doLog(Logger.java:552)
    at java.util.logging.Logger.logp(Logger.java:668)
    at org.apache.juli.logging.DirectJDKLog.log(DirectJDKLog.java:183)
    at org.apache.juli.logging.DirectJDKLog.info(DirectJDKLog.java:126)
    at org.apache.coyote.AbstractProtocol.init(AbstractProtocol.java:376)
    at org.apache.coyote.http11.AbstractHttp11JsseProtocol.init(AbstractHttp11JsseProtocol.java:119)
    at org.apache.catalina.connector.Connector.initInternal(Connector.java:956)
    ... 13 more
```

**Comment by stuart-warren** [comment]
Also fix the issue in the stack trace ;)
