### ISSUE TITLE
Handle exceptions better

### ISSUE THREAD

**Issue by stuart-warren** [stuart-warren/logit#47]
29-Oct-2013 13:21:29 hudson.model.AbstractBuild$AbstractBuildExecution performAllBuildSteps
WARNING: Publisher hudson.tasks.Mailer aborted due to exception
zmq.ZError$IOException: java.nio.channels.ClosedByInterruptException
        at zmq.Signaler.send(Signaler.java:108)
        at zmq.Mailbox.send(Mailbox.java:90)
        at zmq.Ctx.send_command(Ctx.java:351)
        at zmq.ZObject.send_command(ZObject.java:364)
        at zmq.ZObject.send_activate_read(ZObject.java:217)
        at zmq.Pipe.flush(Pipe.java:284)
        at zmq.LB.send(LB.java:120)
        at zmq.Push.xsend(Push.java:64)
        at zmq.SocketBase.send(SocketBase.java:598)
        at org.jeromq.ZMQ$Socket.send(ZMQ.java:932)
        at com.stuartwarren.logit.zmq.ZmqTransport.appendString(ZmqTransport.java:100)
        at com.stuartwarren.logit.jul.ZmqAppender.publish(ZmqAppender.java:76)
        at java.util.logging.Logger.log(Logger.java:481)
        at java.util.logging.Logger.doLog(Logger.java:503)
        at java.util.logging.Logger.log(Logger.java:526)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.search(AbstractLazyLoadRunMap.java:441)
        at hudson.model.AbstractBuild.getPreviousBuild(AbstractBuild.java:218)
        at hudson.tasks.Fingerprinter$FingerprintAction.compact(Fingerprinter.java:356)
        at hudson.tasks.Fingerprinter$FingerprintAction.onLoad(Fingerprinter.java:345)
        at hudson.model.Run.onLoad(Run.java:323)
        at hudson.model.RunMap.retrieve(RunMap.java:226)
        at hudson.model.RunMap.retrieve(RunMap.java:59)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:674)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:657)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.search(AbstractLazyLoadRunMap.java:456)
        at hudson.model.AbstractBuild.getPreviousBuild(AbstractBuild.java:218)
        at hudson.tasks.Fingerprinter$FingerprintAction.compact(Fingerprinter.java:356)
        at hudson.tasks.Fingerprinter$FingerprintAction.onLoad(Fingerprinter.java:345)
        at hudson.model.Run.onLoad(Run.java:323)
        at hudson.model.RunMap.retrieve(RunMap.java:226)
        at hudson.model.RunMap.retrieve(RunMap.java:59)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:674)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:657)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.search(AbstractLazyLoadRunMap.java:456)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.newestBuild(AbstractLazyLoadRunMap.java:321)
        at hudson.model.AbstractProject.getLastBuild(AbstractProject.java:1066)
        at hudson.model.AbstractProject.hasParticipant(AbstractProject.java:1587)
        at hudson.model.User.getProjects(User.java:448)
        at hudson.scm.MailAddressResolverImpl.findMailAddressFor(MailAddressResolverImpl.java:19)
        at hudson.tasks.MailAddressResolver.resolve(MailAddressResolver.java:101)
        at hudson.tasks.MailAddressResolver.resolve(MailAddressResolver.java:101)
        at hudson.tasks.Mailer$UserProperty.getAddress(Mailer.java:532)
        at hudson.tasks.MailSender.buildCulpritList(MailSender.java:408)
        at hudson.tasks.MailSender.createEmptyMail(MailSender.java:368)
        at hudson.tasks.MailSender.createBackToNormalMail(MailSender.java:177)
        at hudson.tasks.MailSender.getMail(MailSender.java:170)
        at hudson.tasks.MailSender.execute(MailSender.java:100)
        at hudson.tasks.Mailer.perform(Mailer.java:117)
        at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
        at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:780)
        at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:752)
        at hudson.model.Build$BuildExecution.post2(Build.java:183)
        at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:705)
        at hudson.model.Run.execute(Run.java:1617)
        at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
        at hudson.model.ResourceController.execute(ResourceController.java:88)
        at hudson.model.Executor.run(Executor.java:237)
Caused by: java.nio.channels.ClosedByInterruptException
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:184)
        at sun.nio.ch.SinkChannelImpl.write(SinkChannelImpl.java:154)
        at zmq.Signaler.send(Signaler.java:106)
        ... 55 more

**Comment by stuart-warren** [comment]
Reopen.

Still weird issues
Possibly an InterruptedException but no stacktrace.

Tweak logging to LogitLog the error but not spam with each message. Add trace mode?

**Comment by stuart-warren** [comment]
Raised question on SO, see:
 http://stackoverflow.com/questions/20066776/zeromq-handle-ioexception-when-logging-from-tomcat

Requested clarification, still waiting...

**Comment by stuart-warren** [comment]
Still not working.
Take a look at http://grepcode.com/file_/repository.grepcode.com/java/root/jdk/openjdk/6-b14/java/util/logging/SocketHandler.java/?v=source
